import os
name = input("Commit name: ")
print("Adding...")
os.system("git --git-dir=.gitpublic add .")
os.system("cls")
print("Public done")
os.system("git --git-dir=.gitprivate add .")
os.system("cls")
print("Added\nCommiting...")
os.system("git --git-dir=.gitpublic commit -m '{0}'".format(name))
os.system("cls")
print("Public done")
os.system("git --git-dir=.gitprivate commit -m '{0}'".format(name))
os.system("cls")
print("Commited.¡\nPushing...")
os.system("git --git-dir=.gitpublic push")
os.system("cls")
print("Public done")
os.system("git --git-dir=.gitprivate push")
os.system("cls")
print("Pushed")